import PropTypes from 'prop-types';

export const gistsArray = {
  'url': PropTypes.string,
  'forks_url': PropTypes.string,
  'commits_url': PropTypes.string,
  'id': PropTypes.string,
  'node_id': PropTypes.string,
  'git_pull_url': PropTypes.string,
  'git_push_url': PropTypes.string,
  'html_url': PropTypes.string,
  'files': PropTypes.shape({}),
  'public': PropTypes.bool,
  'created_at': PropTypes.string,
  'updated_at': PropTypes.string,
  'description': PropTypes.string,
  'comments': PropTypes.number,
  'user': PropTypes.string,
  'comments_url': PropTypes.string,
  'owner': PropTypes.shape({
    'login': PropTypes.string,
    'id': PropTypes.number,
    'node_id': PropTypes.string,
    'avatar_url': PropTypes.string,
    'gravatar_id': PropTypes.string,
    'url': PropTypes.string,
    'html_url': PropTypes.string,
    'followers_url': PropTypes.string,
    'following_url': PropTypes.string,
    'gists_url': PropTypes.string,
    'starred_url': PropTypes.string,
    'subscriptions_url': PropTypes.string,
    'organizations_url': PropTypes.string,
    'repos_url': PropTypes.string,
    'events_url': PropTypes.string,
    'received_events_url': PropTypes.string,
    'type': PropTypes.string,
    'site_admin': PropTypes.bool
  }),
  'truncated': PropTypes.bool
};
